#
# TeleMetrum v1.0 build
#

TM_VER=1.0
TM_DEF=1_0

TM_INC = \
	ao_at45db161d.h

TM_SRC = \
	ao_companion.c \
	ao_gps_skytraq.c \
	ao_gps_show.c \
	ao_at45db161d.c

include ../product/Makefile.telemetrum
