#!/bin/sh
for i in "$@"; do
gnuplot -p << EOF &
set title "$i"
set ylabel "height (m)"
set xlabel "time (s)"
set xtics border out nomirror
set ytics border out nomirror
set y2tics border out nomirror
plot "$i" using 1:2 with lines lt 2 axes x1y1 title "raw height",\
     "$i" using 1:3 with lines lt 4 axes x1y1 title "kalman height",\
     "$i" using 1:4 with lines lt 1 axes x1y1 title "max height"
EOF
done
