#!/bin/sh

DIR=~/misc/rockets/flights

for i in "$@"; do
case "$i" in
    */*)
    file="$i"
    ;;
    *)
    file="$DIR/$i"
    ;;
esac
./ao_flight_test "$file" > run-out.full
./ao_flight_test_baro "$file" > run-out.baro

#./ao_flight_test_accel "$file" > run-out.accel
#"run-out.accel" using 1:9 with lines lt 4 axes x1y1 title "accel height",\
#"run-out.accel" using 1:11 with lines lt 4 axes x1y2 title "accel speed",\
#"run-out.accel" using 1:13 with lines lt 4 axes x1y2 title "accel accel",\
#"run-out.accel" using 1:15 with lines lt 4 axes x1y1 title "accel drogue",\
#"run-out.accel" using 1:17 with lines lt 4 axes x1y1 title "accel main",\
#

gnuplot << EOF
set ylabel "altitude (m)"
set y2label "velocity (m/s), acceleration(m/s²)"
set xlabel "time (s)"
set xtics border out nomirror
set ytics border out nomirror
set y2tics border out nomirror
set title "$i"
plot "run-out.full" using 1:3 with lines lw 2 lt 1 axes x1y1 title "raw height",\
"run-out.full" using 1:5 with lines lw 2 lt 1 axes x1y2 title "raw accel",\
"run-out.full" using 1:9 with lines lt 2 axes x1y1 title "full height",\
"run-out.full" using 1:11 with lines lt 2 axes x1y2 title "full speed",\
"run-out.full" using 1:13 with lines lt 2 axes x1y2 title "full accel",\
"run-out.full" using 1:15 with lines lt 2 axes x1y1 title "full drogue",\
"run-out.full" using 1:17 with lines lt 2 axes x1y1 title "full main", \
"run-out.baro" using 1:9 with lines lt 3 axes x1y1 title "baro height",\
"run-out.baro" using 1:11 with lines lt 3 axes x1y2 title "baro speed",\
"run-out.baro" using 1:13 with lines lt 3 axes x1y2 title "baro accel",\
"run-out.baro" using 1:15 with lines lt 3 axes x1y1 title "baro drogue",\
"run-out.baro" using 1:17 with lines lt 3 axes x1y1 title "baro main"
pause mouse close
EOF
done