#!/bin/sh
HEADER=$1
MEM=$2

HEADER_STACK=`awk '/#define AO_STACK_START/ {print $3}' $HEADER`
MEM_STACK=`awk '/Stack starts at/ {print $4}' $MEM`

if [ "$HEADER_STACK" != "$MEM_STACK" ]; then
	echo "Set AO_STACK_START to $MEM_STACK"
	exit 1
else
	exit 0
fi
