PROG = telelaunch-v0.1-$(VERSION).ihx

SRC = \
	$(TLAUNCH_BASE_SRC) \
	$(SPI_DRIVER_SRC) \
	$(EE_DRIVER_SRC) \
	ao_launch.c \
	ao_aes.c \
	ao_radio_cmac.c \
	$(DBG_SRC)

PRODUCT=TeleLaunch-v0.1
PRODUCT_DEF=-DTELELAUNCH_V_0_1
IDPRODUCT=0x000f
