.\"
.\" Copyright © 2009 Keith Packard <keithp@keithp.com>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
.\"
.\"
.TH AO-EJECTION 1 "ao-ejection" ""
.SH NAME
ao-ejection \- Compute rocket ejection charges
.SH SYNOPSIS
.B "ao-ejection"
\fIdiameter(mm)\fP
\fIlength(mm)\fP
\fIforce(N)\fP
.SH DESCRIPTION
.I ao-ejection
computes the amount of black powder necessary to generate the desired
force to separate sections of a rocket airframe. It assumes a
cylindrical airspace covered by a circular cap. With that and the
force to be exerted on the cap,
.I ao-ejection
can compute the necessary pressure rise within the chamber, the volume
of gas necessary and finally the mass of BP to generate the gas.
.SH EXAMPLE
.nf
	$ ao-ejection 54 300 500
	Input parameters:
	    Diameter: 54.0 (mm) 2.126 (in)
	    Length: 300.0 (mm) 11.811 (in)
	    Force: 500.0 (N) 112.404 (lb)
	Chamber values:
	    Area: 2290 (mm²) 3.550 (in²)
	    Volume: 687066 (mm³) 41.927 (in³)
	    Pressure: 31.66 (lb/in²) 0.21832 (N/mm²)
	Results:
	    FFFF powder: 0.685 (g)
.fi
.P
This demonstrates that a 54mm airframe with a 300mm chamber
requires .685g of FFFF BP to generate 112lb of force on the end of the
chamber. This is usually sufficient to sever two 2x56 nylon screws.
.SH AUTHOR
Keith Packard
