#!/bin/sh

if [ -x /usr/bin/ao-flash-stm ]; then
	STMLOAD=/usr/bin/ao-flash-stm
else
	echo "Can't find ao-flash-stm!  Aborting."
	exit 1
fi

if [ -x /usr/bin/ao-usbload ]; then
	USBLOAD=/usr/bin/ao-usbload
else
	echo "Can't find ao-usbload!  Aborting."
	exit 1
fi

VERSION=1.0
REPO=~/altusmetrumllc/Binaries

echo "TeleMega v$VERSION Turn-On and Calibration Program"
echo "Copyright 2014 by Bdale Garbee.  Released under GPL v2"
echo
echo "Expectations:"
echo "\tTeleMega v$VERSIOn powered from USB"
echo "\t\twith ST-Link-V2 cabled to debug header"
echo "\t\twith coax from UHF to frequency counter"
echo
echo -n "TeleMega-$VERSION serial number: "
read SERIAL

echo $STMLOAD

$STMLOAD $REPO/loaders/telemega-v$VERSION*.elf || exit 1

sleep 2

$USBLOAD --serial=$SERIAL $REPO/telemega-v$VERSION*.elf || exit 1

sleep 2

dev=`ao-list | awk '/TeleMega-v'"$VERSION"'/ { print $3; exit(0); }'`

case "$dev" in
/dev/tty*)
	echo "TeleMega found on $dev"
	;;
*)
	echo 'No TeleMega-v'"$VERSION"' found'
	exit 1
	;;
esac

echo 'E 0' > $dev

SERIAL=$SERIAL ./cal-freq $dev

./cal-accel $dev
