#!/bin/sh

if [ -x ../ao-tools/ao-stmload/ao-stmload ]; then
	STMLOAD=../ao-tools/ao-stmload/ao-stmload
elif [ -x /usr/bin/ao-stmload ]; then
	STMLOAD=/usr/bin/ao-stmload
else
	echo "Can't find ao-stmload!  Aborting."
	exit 1
fi

if [ -x ../ao-tools/ao-usbload/ao-usbload ]; then
	USBLOAD=../ao-tools/ao-usbload/ao-usbload
elif [ -x /usr/bin/ao-usbload ]; then
	USBLOAD=/usr/bin/ao-usbload
else
	echo "Can't find ao-usbload!  Aborting."
	exit 1
fi

VERSION=1.0
#VERSION=0.1

echo "TeleMega v$VERSION Turn-On and Calibration Program"
echo "Copyright 2010 by Bdale Garbee.  Released under GPL v2"
echo
echo "Expectations:"
echo "\tTeleMega v$VERSIOn powered from USB"
echo "\t\twith ST-Link-V2 cabled to debug header"
echo "\t\twith coax from UHF to frequency counter"
echo
echo -n "TeleMega-$VERSION serial number: "
read SERIAL

echo $STMLOAD

$STMLOAD --raw ../src/telemega-v$VERSION/flash-loader/*.elf || exit 1

sleep 2

#$USBLOAD --serial=$SERIAL ../src/telemega-v$VERSION/*.ihx || exit 1
$USBLOAD --serial=$SERIAL /usr/share/altos/telemega-v$VERSION*.ihx || exit 1

sleep 2

dev=`ao-list | awk '/TeleMega-v'"$VERSION"'/ { print $3; exit(0); }'`

case "$dev" in
/dev/tty*)
	echo "TeleMega found on $dev"
	;;
*)
	echo 'No TeleMega-v'"$VERSION"' found'
	exit 1
	;;
esac

echo 'E 0' > $dev

SERIAL=$SERIAL ./cal-freq $dev

./cal-accel $dev
