#!/bin/sh

if [ -x ../ao-tools/ao-stmload/ao-stmload ]; then
	STMLOAD=../ao-tools/ao-stmload/ao-stmload
elif [ -x /usr/bin/ao-stmload ]; then
	STMLOAD=/usr/bin/ao-stmload
else
	echo "Can't find ao-stmload!  Aborting."
	exit 1
fi

if [ -x ../ao-tools/ao-usbload/ao-usbload ]; then
	USBLOAD=../ao-tools/ao-usbload/ao-usbload
elif [ -x /usr/bin/ao-usbload ]; then
	USBLOAD=/usr/bin/ao-usbload
else
	echo "Can't find ao-usbload!  Aborting."
	exit 1
fi

VERSION=2.0

echo "TeleMetrum v$VERSION Turn-On and Calibration Program"
echo "Copyright 2014 by Bdale Garbee.  Released under GPL v2"
echo
echo "Expectations:"
echo "\tTeleMetrum v$VERSIOn powered from USB"
echo "\t\twith ST-Link-V2 cabled to debug header"
echo "\t\twith coax from UHF to frequency counter"
echo
echo -n "TeleMetrum-$VERSION serial number: "
read SERIAL

echo $STMLOAD

$STMLOAD --raw ../src/telemetrum-v$VERSION/flash-loader/*.elf || exit 1

sleep 2

$USBLOAD --serial=$SERIAL /usr/share/altos/telemetrum-v$VERSION*.ihx || exit 1

sleep 5

dev=`ao-list | awk '/TeleMetrum-v'"$VERSION"'/ { print $3; exit(0); }'`

case "$dev" in
/dev/tty*)
	echo "TeleMetrum found on $dev"
	;;
*)
	echo 'No TeleMetrum-v'"$VERSION"' found'
	exit 1
	;;
esac

echo 'E 0' > $dev

SERIAL=$SERIAL ./cal-freq $dev

./cal-accel $dev
