#!/bin/sh

# serial number of the TeleDongle being used as the flash programmer
DONGLE=612

if [ -x ../ao-tools/ao-load/ao-load ]; then
	AOLOAD=../ao-tools/ao-load/ao-load
elif [ -x /usr/bin/ao-load ]; then
	AOLOAD=/usr/bin/ao-load
else
	echo "Can't find ao-load!  Aborting."
	exit 1
fi

if [ -x ../ao-tools/ao-rawload/ao-rawload ]; then
	RAWLOAD=../ao-tools/ao-rawload/ao-rawload
elif [ -x /usr/bin/ao-rawload ]; then
	RAWLOAD=/usr/bin/ao-rawload
else
	echo "Can't find ao-rawload!  Aborting."
	exit 1
fi

echo "TeleBT v1.1 Turn-On and Calibration Program"
echo "Copyright 2013 by Bdale Garbee.  Released under GPL v2"
echo
echo "Expectations:"
echo "\tTeleBT v1.1 powered from USB"
echo "\t\twith TeleDonlge (on /dev/ttyACM0) cabled to debug header"
echo "\t\twith coax from SMA to frequency counter"
echo
echo -n "TeleBT serial number: "
read SERIAL

echo $RAWLOAD

$RAWLOAD -D $DONGLE -r ao_led_blink.ihx
echo "LEDs should be blinking"
sleep 5

$RAWLOAD -D $DONGLE -r ao_radio_xmit.ihx
echo -n "Generating RF carrier.  Please enter measured frequency: "
read FREQ

CAL_VALUE=`nickle -e "floor(434.55 / $FREQ * 1186611 + 0.5)"`

echo "Programming flash with cal value " $CAL_VALUE
$AOLOAD -D $DONGLE --cal $CAL_VALUE /usr/share/altos/telebt-v1.0*.ihx $SERIAL

echo "Serial number "$SERIAL" programmed with RF cal value "$CAL_VALUE
echo $SERIAL","$CAL_VALUE >> cal_values
echo "Unplug debug cable, power cycle, cu to the board, confirm freq and record power"
