#!/bin/sh

if [ -x ../ao-tools/ao-load/ao-load ]; then
	AOLOAD=../ao-tools/ao-load/ao-load
elif [ -x /usr/bin/ao-load ]; then
	AOLOAD=/usr/bin/ao-load
else
	echo "Can't find ao-load!  Aborting."
	exit 1
fi

if [ -x ../ao-tools/ao-rawload/ao-rawload ]; then
	RAWLOAD=../ao-tools/ao-rawload/ao-rawload
elif [ -x /usr/bin/ao-rawload ]; then
	RAWLOAD=/usr/bin/ao-rawload
else
	echo "Can't find ao-rawload!  Aborting."
	exit 1
fi

echo "TeleMetrum v1.0 Turn-On and Calibration Program"
echo "Copyright 2010 by Bdale Garbee.  Released under GPL v2"
echo
echo "Expectations:"
echo "\tTeleMetrum v1.0 powered from USB"
echo "\t\twith TeleDongle (on /dev/ttyACM0) cabled to debug header"
echo "\t\twith coax from UHF to frequency counter"
echo
echo -n "TeleMetrum serial number: "
read SERIAL

echo $RAWLOAD

$RAWLOAD -r ao_led_blink.ihx
echo "the red LED should be blinking"
sleep 5

$RAWLOAD -r ao_radio_xmit.ihx
echo -n "Generating RF carrier.  Please enter measured frequency: "
read FREQ

CAL_VALUE=`nickle -e "floor(434.55 / $FREQ * 1186611 + 0.5)"`

echo "Programming flash with cal value " $CAL_VALUE
$AOLOAD --cal $CAL_VALUE /usr/share/altos/telemetrum-v1.0*.ihx $SERIAL

echo "Serial number "$SERIAL" programmed with RF cal value "$CAL_VALUE
echo "Unplug and replug USB, cu to the board, confirm freq and record power"
