#!/bin/sh

if [ -x ../ao-tools/ao-load/ao-load ]; then
	AOLOAD=../ao-tools/ao-load/ao-load
elif [ -x /usr/bin/ao-load ]; then
	AOLOAD=/usr/bin/ao-load
else
	echo "Can't find ao-load!  Aborting."
	exit 1
fi

if [ -x ../ao-tools/ao-rawload/ao-rawload ]; then
	RAWLOAD=../ao-tools/ao-rawload/ao-rawload
elif [ -x /usr/bin/ao-rawload ]; then
	RAWLOAD=/usr/bin/ao-rawload
else
	echo "Can't find ao-rawload!  Aborting."
	exit 1
fi

echo "TeleTerra v0.2 Turn-On and Calibration Program"
echo "Copyright 2012 by Bdale Garbee.  Released under GPL v2"
echo
echo "Expectations:"
echo "\tTeleTerra v0.2 powered from USB"
echo "\t\twith TeleDongle (on /dev/ttyACM0) cabled to debug header"
echo "\t\twith coax from SMA to frequency counter"
echo
echo -n "TeleTerra serial number: "
read SERIAL

echo $RAWLOAD

$RAWLOAD -D 100 -r ao_led_blink.ihx
echo "LEDs should be blinking"
sleep 5

$RAWLOAD -D 100 -r ao_radio_xmit.ihx
echo -n "Generating RF carrier.  Please enter measured frequency: "
read FREQ

CAL_VALUE=`nickle -e "floor(434.55 / $FREQ * 1186611 + 0.5)"`

echo "Programming flash with cal value " $CAL_VALUE
$AOLOAD -D 100 --cal $CAL_VALUE /home/bdale/debian/altos/src/teleterra-v0.2/*.ihx $SERIAL

echo "Serial number "$SERIAL" programmed with RF cal value "$CAL_VALUE
echo "Unplug and replug USB, cu to the board, confirm freq and record power"
