#!/bin/sh
for i in "$@"; do
gnuplot -p << EOF
set title "$i"
set ylabel "height (m)"
set y2label "speed"
set xlabel "time (s)"
set xtics border out nomirror
set ytics border out nomirror
set y2tics border out nomirror
plot "$i" using 1:3 with lines lt 1 axes x1y1 title "raw height",\
     "$i" using 1:7 with lines lt 2 axes x1y1 title "kalman height",\
     "$i" using 1:8 with lines lt 3 axes x1y1 title "max height",\
     "$i" using 1:6 with lines lt 4 axes x1y2 title "kalman accel",\
     "$i" using 1:12 with lines lt 5 axes x1y2 title "valid"
EOF
done
