#!/bin/sh
for i in "$@"; do
gnuplot -p << EOF
set title "$i"
set ylabel "height (m)"
set y2label "velocity (m/s), acceleration (m/s²)"
set xlabel "time (s)"
set xtics border out nomirror
set ytics border out nomirror
set y2tics border out nomirror
plot "$i" using 1:2 with lines lt 1 axes x1y1 title "raw height",\
     "$i" using 1:3 with lines lt 1 axes x1y2 title "raw speed",\
     "$i" using 1:4 with lines lt 1 axes x1y2 title "raw accel",\
     "$i" using 1:5 with lines lt 2 axes x1y1 title "both height",\
     "$i" using 1:6 with lines lt 2 axes x1y2 title "both vel",\
     "$i" using 1:7 with lines lt 2 axes x1y2 title "both accel",\
     "$i" using 1:8 with lines lt 3 axes x1y1 title "accel height",\
     "$i" using 1:9 with lines lt 3 axes x1y2 title "accel vel",\
     "$i" using 1:10 with lines lt 3 axes x1y2 title "accel accel",\
     "$i" using 1:11 with lines lt 4 axes x1y1 title "baro height",\
     "$i" using 1:12 with lines lt 4 axes x1y2 title "baro vel",\
     "$i" using 1:13 with lines lt 4 axes x1y2 title "baro accel"
EOF
done
