#!/bin/sh
#for M in 10 20 50 100 200 500; do
#for M in 50 100 200; do
for M in 2 5 10; do
	for i in *.csv; do
		micro=`basename $i .csv`-$M.micro
		echo $i '->' $micro
		nickle ./kalman_micro.5c -M $M $i > $micro
	done
done
