/.\"
.\" Copyright © 2009 Keith Packard <keithp@keithp.com>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
.\"
.\"
.TH AO-LIST 1 "ao-list" ""
.SH NAME
ao-list \- List connected AltOS devices
.SH SYNOPSIS
.B "ao-list"
.SH DESCRIPTION
.I ao-list
scans the attached USB devices, locates those running AltOS and
displays their product name and serial number along with the tty
device associated with the serial port over USB provided by AltOS.
.SH USAGE
.I ao-list
.SH AUTHOR
Keith Packard
